### ISSUE TITLE
关于中间件运行时的一个不成熟的小问题

### ISSUE THREAD

**Issue by nutllwhy** [csvwolf/Sky_Message_Routing_Middleware#1]
在做测试的时候，为了测试不同情况下的后端会给中间件的收发带来什么影响，我们尝试了这段代码
from websocket import create_connection
import json
ws = create_connection('ws://localhost:8888')
print 'Sending "Hello World"'
initMessage = {'type': 'ass', 'descrption': 'hello world', 'command': 'new', 'content': None}
ws.send(json.dumps(initMessage))
times = 0
while True:
    times += 1
    result = ws.recv()
    print 'Received "%s"' % result
    #result = json.loads(result)
    result2 = json.loads(result)
    print 'Load "%s"' % result2
    answer = result2
    print 'LoadAnswer "%s"' % answer
    **del answer['type']**
    print 'DelAnswer "%s"' % answer
    answer['command'] = 'message'
    **#answer['content'] = 'test one'**
    answer2 = json.dumps(answer)
    print 'Send "%s"' % answer2
    ws.send(answer2)

重点在加粗的两句，总之上一次我们的操作就是，删掉了type字段，同时，把content的内容改成test one。在这一次测试中，我们把修改content内容的那句注释了。
不知道是不是因为我们反复的尝试开关后端服务器，在这次测试中，开启服务器之后，后端收不到任何语句，除了正常输出hello world，其他什么都没有。
我们观察了一下前端的控制台，正常返回，也没有报“No server”的错，中间件也正常收到了前端发来的内容，在返回的时候，也的确删掉了type字段，没有报错。

然后，我尝试把注释取消（也就是恢复对content内容的更改），重启服务器之后，后端的控制台还是没有输出除了hello world之外的语句。
观察了一下前端控制台，正常输出，但这次content内容没有改变。
观察了一下中间件，正常运作，但是可以注意到，返回给前端的数据没有被修改。还是保持前端发来的数据。但是type字段又是的的确确被删掉了。
总裁那边尝试一下，没有我这个问题，我就想这个可能是偶然性的，经过对中间件的重启，一切恢复，后端开始可以正常收发内容，对content的修改也生效了。

不知道这个算不算中间件的问题，又或者是我们操作上的失误，还是先报上来了。

**Comment by csvwolf** [comment]
操作错误：

```
answer['content'] = 'test one'
```

<del>修改回复内容时发送的是`answer2`的值，而修改时修改针对的是`answer`，`answer`和`answer2`没有直接关联。</del>

另外`type`是由服务器注册时决定（也就是发送`create`命令），而不是中途发送可修改的。

经过测试，该问题无法复现，请提交复现条件或者考虑操作错误。

**Comment by csvwolf** [comment]
--- 经讨论：发起人无法复现，关闭issue ---
